### ISSUE TITLE
Unicode Font Encode Error

### ISSUE THREAD

**Issue by not94** [yuzutech/kroki#1388]
I have tried the official blockdig example but it doesn't work in https://kroki.io/.It shows encode error:
<img width="1107" alt="截屏2022-11-16 19 39 32" src="https://user-images.githubusercontent.com/30224079/202171236-1704b627-27f6-4053-b82e-fd3af25dc8a9.png">

Here is the example I use : http://blockdiag.com/en/blockdiag/examples.html#mutlilingualization.

I remember  https://kroki.io/. was ok with this example before.Maybe something changed since last website release.I will be deeply appreciated that website maintainer has done and look forward to your reply.😉

**Comment by Mogztter** [comment]
It seems to be a bug/limitation in https://github.com/python-pillow/Pillow:

```py
# coding: utf-8
import sys
from PIL import Image, ImageDraw

out = Image.new("RGB", (150, 100), (255, 255, 255))

draw = ImageDraw.Draw(out)
bbox = draw.textbbox(text='春', xy=(0,0), font=None)
```
```
Traceback (most recent call last):
  File "/home/guillaume/workspace/yuzutech/kroki/pil/test.py", line 8, in <module>
    bbox = draw.textbbox(text='春', xy=(0,0), font=None)
  File "/home/guillaume/workspace/yuzutech/kroki/pil/.venv/lib/python3.10/site-packages/PIL/ImageDraw.py", line 729, in textbbox
    bbox = font.getbbox(
  File "/home/guillaume/workspace/yuzutech/kroki/pil/.venv/lib/python3.10/site-packages/PIL/ImageFont.py", line 189, in getbbox
    width, height = self.font.getsize(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u6625' in position 0: ordinal not in range(256)
```
