### ISSUE TITLE
UMlet returns HTTP 500 error on arm64 host

### ISSUE THREAD

**Issue by FelixVanOost** [yuzutech/kroki#1524]
UMlet returns the following HTTP 500 error when attempting to convert a diagram on a native `arm64` host:

```java
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". SLF4J: Defaulting to no-operation
(NOP) logger implementation SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for
further details. Exception in thread "main" java.lang.ExceptionInInitializerError at
org.mozilla.javascript.Context.getCurrentContext(Context.java:413) at
org.mozilla.javascript.ScriptableObject.createSlotMap(ScriptableObject.java:367) at
org.mozilla.javascript.ScriptableObject.(ScriptableObject.java:376) at
com.baselet.diagram.draw.swing.javascriptparser.DrawerScriptable.(DrawerScriptable.java:17) at
com.baselet.diagram.draw.swing.javascriptparser.JavascriptParserSwing(JavascriptParserSwing.java:21) at com.baselet.diagram.draw.swing.DrawHandlerSwing(DrawHandlerSwing.java:40) at com.baselet.element.ComponentSwing.(ComponentSwing.java:25) at
com.baselet.element.ElementFactorySwing.create(ElementFactorySwing.java:28) at
com.baselet.diagram.io.InputHandler.endElement(InputHandler.java:94) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractAXParser.java:610) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635) at
java.xml@11.0.18/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324) at java.xml@11.0.18/javax.xml.parsers.SAXParser.parse(SAXParser.java:197) at
com.baselet.diagram.io.DiagramFileHandler.parse(DiagramFileHandler.java:179) at
com.baselet.diagram.io.DiagramFileHandler.doParse(DiagramFileHandler.java:188) at
com.baselet.diagram.DiagramHandler.(DiagramHandler.java:54) at
com.baselet.diagram.DiagramHandler.forExport(DiagramHandler.java:44) at
io.kroki.umlet.UmletConverter.convert(UmletConverter.java:25) at
io.kroki.umlet.UmletCli.main(UmletCli.java:13) Caused by: java.lang.IllegalStateException: Failed to create VMBridge instance at org.mozilla.javascript.VMBridge.makeInstance(VMBridge.java:35) at org.mozilla.javascript.VMBridge.(VMBridge.java:17) ... 27 more (exit code 1)
```

**Comment by ggrossetie** [comment]
Are you testing from the latest release or from the main branch? We are now using a native binary: https://github.com/yuzutech/umlet/releases/

**Comment by FelixVanOost** [comment]
Sorry, I forgot to include the version 🤦🏻‍♂️. This is from `main` commit 83915 using the native binary.

**Comment by ggrossetie** [comment]
Could you please share your diagram? Rhino (JavaScript engine) is using [dynamic classloading](https://github.com/mozilla/rhino/blob/a3ac11a1eff1115d357b136df4f9d6176f1a2389/src/org/mozilla/javascript/VMBridge.java#L19-L36) and we need to trigger this code path otherwise it won't be included in the native image.

**Comment by FelixVanOost** [comment]
This was with the default UMlet example from Niolesk:

```
<diagram><zoom_level>10</zoom_level><element><id>UMLClass</id><coordinates><x>260</x><y>90</y><w>210</w><h>190</h></coordinates><panel_attributes>&lt;&lt;Stereotype&gt;&gt;
Package::FatClass
{Some Properties}
--
-id: Long
_-ClassAttribute: Long_
--
#Operation(i: int): int
/+AbstractOperation()/
--
Responsibilities
-- Resp1
*-- Resp2*</panel_attributes><additional_attributes></additional_attributes></element><element><id>UMLClass</id><coordinates><x>260</x><y>340</y><w>210</w><h>70</h></coordinat…t;&gt;</panel_attributes><additional_attributes>10;10;10;70</additional_attributes></element><element><id>UMLClass</id><coordinates><x>260</x><y>50</y><w>100</w><h>30</h></coordinates><panel_attributes>SimpleClass</panel_attributes><additional_attributes></additional_attributes></element><element><id>UMLClass</id><coordinates><x>370</x><y>50</y><w>100</w><h>30</h></coordinates><panel_attributes>/AbstractClass/
</panel_attributes><additional_attributes></additional_attributes></element></diagram>
```

**Comment by ggrossetie** [comment]
I have published a new version https://github.com/yuzutech/umlet/releases/tag/2023-03-20_UMLet_v15.1 could you please test if it's working?

Usage:

 ```
cat diagram.xml | ./umlet-linux-arm64 svg
```

It should also support `png` and `jpeg` (as command argument)

**Comment by ggrossetie** [comment]
Seems to be running fine on my ARM64 Ampere machine.

**Comment by FelixVanOost** [comment]
Working for me too. Thanks!
