### ISSUE TITLE
excalidraw Unable to convert the diagram TimeoutError running on kubernetes

### ISSUE THREAD

**Issue by williamjoy** [yuzutech/kroki#1529]
Seeing the timeout error for every requests when excalidraw is running on k8s (amd64 arch), it used to work fine for older versions, but is failing recently.  I also tried  to use image `yuzutech/kroki-excalidraw:latest` or local docker build same results. 
```log
│ Chrome accepting connections on endpoint ws://127.0.0.1:36423/devtools/browser/4c3d871c-40c0-4be6-a639-15f3c00120f2                                                                                                                 │
│ Unable to convert the diagram TimeoutError: Navigation timeout of 30000 ms exceeded                                                                                                                                                 │
│     at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (/snapshot/app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:146:12)                                                                           │
│ e TimeoutError: Navigation timeout of 30000 ms exceeded                                                                                                                                                                             │
│     at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (/snapshot/app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:146:12)                                                                           │
│                                                                                                                                                               
```

Running on docker seems fine on both arm64 and amd64 arch
```bash
➜  ~ docker run  -p 8004:8004 kroki-excalidraw
Chrome accepting connections on endpoint ws://127.0.0.1:36059/devtools/browser/6c4595f4-b866-4075-8457-3b40355a809d

➜  ~ http  post  http://localhost:8004/excalidraw/svg --timeout 35 < example.json          
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 27027
Content-Type: image/svg+xml
Date: Thu, 27 Apr 2023 21:20:50 GMT
Keep-Alive: timeout=5

<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 840 560" width="840" height="560">
  <!-- svg-source:excalidraw -->
  
  <defs>
    <style class="style-fonts">
      @font-face {
        font-family: "Virgil";
        src: url("https://unpkg.com/@excalidraw/excalidraw@0.15.2/dist/excalidraw-assets/Virgil.woff2");
      }
      @font-face {
        font-family: "Cascadia";
        src: url("https://unpkg.com/@excalidraw/excalidraw@0.15.2/dist/excalidraw-assets/Cascadia.woff2");
      }


    </style>
  </defs>
  <rect x="0" y="0" width="840" height="560" fill="#ffffff"></rect><g stroke-linecap="round" transform="translate(70 210) rotate(0 40 10)"><path d="M0 0 C0 0, 0 0, 0 0 M0 0 C0 0, 0 0, 0 0 M0.32 6.96 C1.62 4.8, 2.93 1.6, 5.48 0.96 M0.02 6.47 C1.12 4.83, 1.97 3.79, 4.98 0.76 M0.94 11.44 C2.83 9.31, 6.57 6.94, 9.74 0.52 M-0.07 11.89 C2.65 9.78, 6.01 5.35, 11.06 0.28 M-0.5 20.22 C7.67 10.43, 10.78 4.15, 16.49 -0.26 M-0.5 18.07 C4.59 12.33, 10.38 5.25, 16.27 0.95 M3.72 20.7 C7.8 18.56, 8.66 10.57, 20.77 -0.43 
```
[example.json](https://github.com/yuzutech/kroki/files/11348085/example.json.txt)

If I build docker image with df75f671b240b98a44cf62f8023b04836210d74e revision, it works on k8s. Can you take a look what could be broken since?

**Comment by ggrossetie** [comment]
Might be a resource limit on k8s? If it's working fine using Docker there must be a limitation/restriction on k8s.

**Comment by ggrossetie** [comment]
We can continue this discussion on https://kroki.zulipchat.com/
