### ISSUE TITLE
UMLet: better error messages / handling in case of invalid xml

### ISSUE THREAD

**Issue by deining** [yuzutech/kroki#1556]
**Reproduction**:

Retrieve an UMLet diagram with the diagram source containing invalid xml, e-g.:

```
<diagram></nonsense>
```

An error is reported: `bip... bip... something wrong happened!`

```
Error 400: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: Unable to parse the source
        at com.baselet.diagram.io.DiagramFileHandler.doParse(DiagramFileHandler.java:190)
        at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:54)
        at com.baselet.diagram.DiagramHandler.forExport(DiagramHandler.java:44)
        at io.kroki.umlet.UmletConverter.convert(UmletConverter.java:25)
        at io.kroki.umlet.UmletCli.main(UmletCli.java:13)
Caused by: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 3; The element type "diagram" must be terminated by the matching end-tag "</diagram>".
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1685)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml@11.0.18/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
        at java.xml@11.0.18/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
        at com.baselet.diagram.io.DiagramFileHandler.parse(DiagramFileHandler.java:179)
        at com.baselet.diagram.io.DiagramFileHandler.doParse(DiagramFileHandler.java:188)
        ... 4 more
```

Were great if a shorter error message were given instead of this long stack trace.

**Comment by ggrossetie** [comment]
The main "issue" is that UMLet throws a `RuntimeException` which is very broad. Having said that, I think we could catch any `RuntimeException` in `UmletConverter` and check if the cause is a `SAXParseException`.


https://github.com/yuzutech/umlet/blob/mini/umlet-cli/src/main/java/io/kroki/umlet/UmletConverter.java

That would allow us to extract the error message:

```
lineNumber: 1; columnNumber: 12; The element type "diagram" must be terminated by the matching end-tag ""
```

Regarding SLF4J warnings/errors, I need to investigate.
