### ISSUE TITLE
Ditaa diagram options are not working

### ISSUE THREAD

**Issue by gladykov** [yuzutech/kroki#1803]
According to this https://github.com/yuzutech/kroki/issues/1279 , diagram options should work.

But when using examples from here:
https://plantuml.com/ditaa

example: 

```
@startditaa < --no-shadows, scale=0.7
+---------+  /--------\   +-------+
| cBLU    +--+cAAA    +---+Version|
|         |  |  Data  |   |   V3  |
|    +----+  |  Base  |   |cRED{d}|
|    |cPNK|  |     {s}|   +-------+
|    |    |  \---+----/
+----+----+    
@endditaa
```

Renders as:
![image](https://github.com/user-attachments/assets/e3607dae-cd06-42bf-9054-e231a0ee8edc)

in https://kroki.io/#try

**Comment by ggrossetie** [comment]
PlantUML embeds ditaa so the following syntax is recognized only by PlantUML:

```
@startditaa < --no-shadows, scale=0.7
(...)
@endditaa
```

When using the ditaa endpoint in Kroki, you should pass diagram options as described in the documentation:

```
https://kroki.io/ditaa/svg/eNrT1oUBbQUFfRg7RkFBQRsmzlWjkOzkE6oAEdNOdnR0hLJ1tcNSi4oz8_NqgGpgoAaMXBJLEsEMMA4zBtIQNdpQu4Acp8TiVKia5CBXl-qUWqiamuQAP2-IOUBQXVxbg-YeqLEgIgYkBBLX54IYDTVfQQEAZBMvuw==?no-shadows
```

<img src="https://kroki.io/ditaa/svg/eNrT1oUBbQUFfRg7RkFBQRsmzlWjkOzkE6oAEdNOdnR0hLJ1tcNSi4oz8_NqgGpgoAaMXBJLEsEMMA4zBtIQNdpQu4Acp8TiVKia5CBXl-qUWqiamuQAP2-IOUBQXVxbg-YeqLEgIgYkBBLX54IYDTVfQQEAZBMvuw==?no-shadows"/>

```
https://kroki.io/ditaa/svg/eNrT1oUBbQUFfRg7RkFBQRsmzlWjkOzkE6oAEdNOdnR0hLJ1tcNSi4oz8_NqgGpgoAaMXBJLEsEMMA4zBtIQNdpQu4Acp8TiVKia5CBXl-qUWqiamuQAP2-IOUBQXVxbg-YeqLEgIgYkBBLX54IYDTVfQQEAZBMvuw==
```

<img src="https://kroki.io/ditaa/svg/eNrT1oUBbQUFfRg7RkFBQRsmzlWjkOzkE6oAEdNOdnR0hLJ1tcNSi4oz8_NqgGpgoAaMXBJLEsEMMA4zBtIQNdpQu4Acp8TiVKia5CBXl-qUWqiamuQAP2-IOUBQXVxbg-YeqLEgIgYkBBLX54IYDTVfQQEAZBMvuw=="/>

It seems that the scale option does not work properly. I get the following error:

```
java.io.FileNotFoundException: --scale 0.7 (No such file or directory) at java.base@11.0.18/java.io.FileInputStream.open0(FileInputStream.java) at java.base@11.0.18/java.io.FileInputStream.open(FileInputStream.java:219) at java.base@11.0.18/java.io.FileInputStream.(FileInputStream.java:157) at java.base@11.0.18/java.io.FileInputStream.(FileInputStream.java:112) at org.stathissideris.ditaa.core.CommandLineConverter.convert(CommandLineConverter.java:72) at org.stathissideris.ditaa.core.CommandLineConverter.main(CommandLineConverter.java:40) (exit code 1)
```

**Comment by gladykov** [comment]
I have no strong opinion here. Just encountered this situation while browsing examples and experimenting with Kroki.
